name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - uses: actions/checkout@master
      - name: Build site
        run: "npm install && npm run build"
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.5.3
        with: 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN_MAIN_SITE }}
          BRANCH: gh-pages
          FOLDER: build
          
         
